# Generated by Django 3.1.7 on 2021-03-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210308_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='owner',
        ),
    ]
