# Generated by Django 3.1.7 on 2021-03-13 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0003_auto_20210312_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('owner', 'tour_instance')},
        ),
    ]
