# Generated by Django 3.1.7 on 2021-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20210313_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='tours_main'),
        ),
    ]
